### ISSUE TITLE
Text within list item breaks numbering

### ISSUE THREAD

**Issue by Valentin271** [trimental/inlyne#174]
Before starting I wanted to thank you for your work, inlyne is a really amazing tool I love it!

# Description

Inlyne version **0.3.2** doesn't render numbered lists correctly in some scenarios, see attached screenshot.

![image](https://github.com/trimental/inlyne/assets/36198422/d404b179-b4f6-4635-9452-2df00a33d531)

It seems like numbered lists with blanklines remove numbering completely.

# Reproduce

Just open the [Ratatui release file](https://github.com/ratatui-org/ratatui/blob/main/RELEASE.md).

# Correct behavior

I won't get into details here are inlyne main branch seems to have a functioning behavior.

# Additional info

The bug also occurs in 0.3.1.

It works perfectly with the main branch of inlyne though, so maybe there isn't even something to fix ...

_PS: feel free to rename the issue to something more expressive_

**Comment by CosmicHorrorDev** [comment]
Thanks for the very detailed bug report!

> It works perfectly with the main branch of inlyne though, so maybe there isn't even something to fix ...

Well that should make the fix easy at the very least. The `main` branch isn't 100% right since it doesn't indent the nested element, but it does correctly keep the lists number/bullet which is good

I'll work on backporting the fix and releasing v0.3.3 over the next few days (intentionally going slow in case any other issues pop up with v0.3.2)

**Comment by CosmicHorrorDev** [comment]
This should be fixed with the v0.3.3 release

https://github.com/trimental/inlyne/releases/tag/v0.3.3
