### ISSUE TITLE
Image loading thread panics when given a non-image payload

### ISSUE THREAD

**Issue by virtualritz** [trimental/inlyne#184]
I tried `inlyne` on the [`README.md`](https://github.com/virtualritz/glyphana/blob/master/README.md) of my `glyphana` crate.
It looks like it chokes on the inlined PNG.  I get:

```toml
"name" = "inlyne"
"operating_system" = "Ubuntu 23.10 (mantic) [64-bit]"
"crate_version" = "0.3.3"
"explanation" = """
Panic occurred in file '/home/moritz/.cargo/registry/src/index.crates.io-6f17d22bba15001f/inlyne-0.3.3/src/image/mod.rs' at line 213
"""
"cause" = "called `Result::unwrap()` on an `Err` value: ParsingFailed(ParserError(UnknownToken(TextPos { row: 1, col: 1 })))"
"method" = "Panic"
"backtrace" = """

   0: 0x5564542066d3 - core::result::unwrap_failed::ha4f4d0d3df67138e
                at /rustc/e9013ac0e402ef449c5d00251d687289599137df/library/core/src/result.rs:1649
   1: 0x5564533877e9 - std::sys_common::backtrace::__rust_begin_short_backtrace::hc09602336b08cc26
   2: 0x556453469d14 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h27a94b36ed1f5707
   3: 0x5564541dd875 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::he3e410b3c6d7ab8b
                at /rustc/e9013ac0e402ef449c5d00251d687289599137df/library/alloc/src/boxed.rs:2007
                 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h9192100527b5956f
                at /rustc/e9013ac0e402ef449c5d00251d687289599137df/library/alloc/src/boxed.rs:2007
                 - std::sys::unix::thread::Thread::new::thread_start::h51e269f565ae77c2
                at /rustc/e9013ac0e402ef449c5d00251d687289599137df/library/std/src/sys/unix/thread.rs:108
   4: 0x7fb233897ada - start_thread
                at ./nptl/pthread_create.c:444
   5: 0x7fb23392847c - __GI___clone3
                at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
   6:        0x0 - <unresolved>"""
```

**Comment by CosmicHorrorDev** [comment]
Thanks for the crash report!

You're right that it's `inlyne` choking on the PNG, although I think this is more of github papering over an issue instead of `inlyne` doing anything wrong. The image link you're using is actually returning a JSON payload which is causing the image parsing to get confused and choke. Github just recognizes the address and can make things work anyways, but it doesn't work everywhere like comments e.g.

---

# Glyphana

[![Build Status](https://github.com/virtualritz/glyphana/workflows/CI/badge.svg)](https://github.com/virtualritz/glyphana/actions?workflow=CI)

Glyphana is a tool to search for and discover unicode glyphs.

It is inspired by the [macOS Character Viewer](https://support.apple.com/guide/mac-help/use-emoji-and-symbols-on-mac-mchlp1560/mac)
which I sorely miss on Linux and Windows.

![Searching for the characters contained in 'grinning cat' as well as matching
the term against each glyph's description](https://github.com/virtualritz/glyphana/blob/master/screenshot.png)

---

or if you were to publish to something like crates.io. Considering how spotty the support for handling this is I think it would be better if the README was switched to using either of the following links instead

- https://github.com/virtualritz/glyphana/blob/master/screenshot.png?raw=true
- https://raw.githubusercontent.com/virtualritz/glyphana/master/screenshot.png

---

_Aside: Also worth mentioning that `inlyne` currently doesn't visually indicate that an image failed loading, but it probably should_

**Comment by virtualritz** [comment]
> Considering how spotty the support for handling this is I think it would be better if the README was switched to using either of the following links instead [...]

Good point. I changed to the other format you suggested.

I.e. this can be closed unless you want to keep it open to track the ungraceful exit of `inlyne` in case of the other URL.

**Comment by CosmicHorrorDev** [comment]
> unless you want to keep it open to track the ungraceful exit of inlyne in case of the other URL.

That's my intention as long as you don't mind me keeping your issue open for longer!
