### ISSUE TITLE
Zoom-in accelerator requires `Shift` on US keyboard layout

### ISSUE THREAD

**Issue by virtualritz** [trimental/inlyne#186]
The standard on Windows/Linux is for `Ctrl`+`+` to zoom. However, this considers the `+` key, not the `+` character. Meaning that on an US keyboard, you have to press `Ctrl`+`=` (the `=` key is actually `=/+` (*equals sign* resp. *plus sign* w. `Shift`).

However, `inlyne` considers the character, so here you have to press `Ctrl`+`Shift`+`=` resp. `Ctrl`+`Shift`+`+` (assuming an US keyboard). 

To see what I mean, try `Ctrl`+`+` in FF, Chrome, VSCode, Photoshop, etc. You never need `Shift`.

**Comment by CosmicHorrorDev** [comment]
That's a good point that I hadn't considered. Currently `Ctrl`+`=` is the keybinding for resetting the zoom, but we really should be trying to better match well known program's keybindings. Switching that will have to be a breaking change, but it also gives us a good chance to evaluate the new `winit` update since that had a lot of changes that should hopefully fix keyboard issues that we were having

**Comment by virtualritz** [comment]
Thanks heasps! :grin:
