### ISSUE TITLE
Scrollbar papercuts

### ISSUE THREAD

**Issue by LovecraftianHorror** [trimental/inlyne#42]
_I'm going to be too busy for the rest of the month to work on OSS, but I figured I would open some issues while I had them in mind_

There are some small papercuts when it comes to using the scrollbar:

- The scrollbar only registers when the mouse cursor is being moved while LMB is held, instead of registering on LMB press
- The scrollbar is help from slightly above the center of the scrollbar instead of the center
- It would be nice if you could grab a specific spot on the scrollbar instead of having it always jump to being held in the center

https://user-images.githubusercontent.com/30302768/189544721-6e4033d5-7c06-45ca-be59-aeb7b083c6e5.mp4

**Comment by trimental** [comment]
I think I should have solved all of these points in commit https://github.com/trimental/inlyne/commit/0a98f0dd9700acf3763d0a0ca7beb5690a22c691. 

The first problem was an obvious bug of mismatching the scrollbar bounds that I didn't notice due to hidpi scaling.

The second was a less obvious bug to do with the rendering of the scrollbar and where scroll y was being set.

The third I had to make `scrollbar_held` an option of a f32 that stores the pixel y position difference between the middle of the scrollbar and the mouse location in order to maintain that distance.

**Comment by trimental** [comment]
Please test it out and tell me if you think it solves these 😄
