### ISSUE TITLE
Maintain focus when zooming and resizing

### ISSUE THREAD

**Issue by LovecraftianHorror** [trimental/inlyne#46]
Currently `inlyne` will keep the same scroll position when resizing and zooming. These actions can cause the layout to change which is perceived as the content jumping around if you are scroll down somewhere in the page. Instead we could get the position of some text somewhere on the screen (center, or maybe top?) and use that to judge what the scroll position should be after resizing/zooming?

Little clip to demonstrate the issue

https://user-images.githubusercontent.com/30302768/189552439-815f0b1e-c931-40b1-9f6f-133ab9bf6db0.mp4

**Comment by trimental** [comment]
The solution I tried for this turned out a lot better and simpler then I expected. Please see if commit https://github.com/trimental/inlyne/commit/750f1c4a946ab16c467280380c54d5464c8f4752 fixes this issue for you.

Basically it just works out how much vertical space of content was on the screen before resizing and then after. It then just multiplies `scroll_y` by that ratio. I'm shocked it only took 11 lines of code change to fix this.
